
create table app_user (
    id number(19,0) generated by default as identity, 
    approved number(1,0) not null check (approved in (0,1)), 
    email varchar2(255 char), first_name varchar2(255 char), 
    last_name varchar2(255 char), password varchar2(255 char), 
    role number(3,0) check (role between 0 and 3), 
    primary key (id)
);

create table password_reset_token (
    id number(19,0) generated by default as identity, 
    expiry_date timestamp(6) with time zone, 
    token varchar2(255 char), 
    verified number(1,0) not null check (verified in (0,1)), 
    user_id number(19,0) not null, 
    primary key (id)
);

create table bank (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    primary key (id)
);

create table bank_account (
    id number(19,0) generated by default as identity, 
    account_name varchar2(255 char), 
    account_number varchar2(255 char), 
    iban varchar2(255 char), 
    bank_id number(19,0) not null, 
    organization_id number(19,0), 
    primary key (id),
    CONSTRAINT fk_bankaccount_bank FOREIGN KEY (bank_id) REFERENCES bank(id),
    CONSTRAINT fk_bankaccount_org FOREIGN KEY (organization_id) REFERENCES organization(id)
);

create table biller (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    primary key (id)
);

create table business (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    primary key (id)
);

create table cost_center (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    description varchar2(255 char), 
    primary key (id)
);

create table expense_account (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    primary key (id)
);

create table legal_entity (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    primary key (id)
);

create table location (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    primary key (id)
);

create table vendor (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    biller_id number(19,0) not null, 
    primary key (id),
    CONSTRAINT fk_vendor_biller FOREIGN KEY (biller_id) REFERENCES biller(id)
);

create table vendor_site (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    vendor_id number(19,0) not null, 
    primary key (id),
    CONSTRAINT fk_vendorsite_vendor FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

create table invoice_type (
    id number(19,0) generated by default as identity, 
    name varchar2(255 char), 
    primary key (id)
);

create table organization (
    id number(19,0) generated by default as identity, 
    code varchar2(255 char), 
    name varchar2(255 char), 
    primary key (id)
);

create table sadad_record (
    id number(19,0) generated by default as identity, 
    amount number(38,2),
    created_at timestamp(6), 
    created_by varchar2(255 char), 
    invoice_number varchar2(255 char), 
    status number(3,0) check (status between 0 and 4), 
    subscription_account_number varchar2(255 char),
    updated_at timestamp(6), 
    updated_by varchar2(255 char), 
    bank_account_id number(19,0), 
    biller_id number(19,0), 
    business_id number(19,0), 
    expense_account_id number(19,0), 
    invoice_type_id number(19,0), 
    legal_entity_id number(19,0), 
    location_id number(19,0), 
    organization_id number(19,0), 
    remitter_bank_id number(19,0), 
    vendor_id number(19,0), 
    vendor_site_id number(19,0), 
    primary key (id),
    CONSTRAINT fk_sadad_org FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT fk_sadad_legal FOREIGN KEY (legal_entity_id) REFERENCES legal_entity(id),
    CONSTRAINT fk_sadad_remitbank FOREIGN KEY (remitter_bank_id) REFERENCES bank(id),
    CONSTRAINT fk_sadad_bankacc FOREIGN KEY (bank_account_id) REFERENCES bank_account(id),
    CONSTRAINT fk_sadad_biller FOREIGN KEY (biller_id) REFERENCES biller(id),
    CONSTRAINT fk_sadad_vendor FOREIGN KEY (vendor_id) REFERENCES vendor(id),
    CONSTRAINT fk_sadad_vendorsite FOREIGN KEY (vendor_site_id) REFERENCES vendor_site(id),
    CONSTRAINT fk_sadad_invtype FOREIGN KEY (invoice_type_id) REFERENCES invoice_type(id),
    CONSTRAINT fk_sadad_expense FOREIGN KEY (expense_account_id) REFERENCES expense_account(id),
    CONSTRAINT fk_sadad_business FOREIGN KEY (business_id) REFERENCES business(id),
    CONSTRAINT fk_sadad_location FOREIGN KEY (location_id) REFERENCES location(id)
)

create table organization_bank (
    organization_id number(19,0) not null, 
    bank_id number(19,0) not null, 
    primary key (organization_id, bank_id)
    CONSTRAINT fk_orgbank_org FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT fk_orgbank_bank FOREIGN KEY (bank_id) REFERENCES bank(id)
);


create table sadad_cost_center (
    id number(19,0) generated by default as identity, 
    percentage number(38,2), 
    cost_center_id number(19,0) not null, 
    sadad_record_id number(19,0) not null, 
    primary key (id),
    CONSTRAINT fk_sadadcc_sadad FOREIGN KEY (sadad_record_id) REFERENCES sadad_record(id),
    CONSTRAINT fk_sadadcc_cost FOREIGN KEY (cost_center_id) REFERENCES cost_center(id)
);


create table fusion_invoice (
    id number(19,0) generated by default as identity, 
    amount number(38,2), 
    invoice_date date, 
    invoice_number varchar2(255 char), 
    invoice_type varchar2(255 char), 
    supplier_name varchar2(255 char), 
    primary key (id)
);
